### ISSUE TITLE
Optimization summary incorrect

### ISSUE THREAD

**Issue by msperryucsd** [anugrahjo/PySLSQP#1] opened 2024-08-10 00:07 UTC
Optimization summary statements show average derivative time instead of average forward time and vice versa:

Example:
Optimization terminated successfully    (Exit mode 0)
            Final objective value                : 6.598148e-11
            Final optimality                     : 1.319630e-10
            Final feasibility                    : 4.840572e-14
            Number of major iterations           : 5
            Number of function evaluations       : 5
            Number of derivative evaluations     : 5
            **Average Derivative evaluation time   : 0.001741 s per evaluation
            Average Function evaluation time     : 0.060738 s per evaluation**
            Total Function evaluation time       : 0.008703 s [  0.08%]
            Total Derivative evaluation time     : 0.303692 s [  2.76%]
            Optimizer time                       : 10.675094 s [ 96.94%]
            Processing time                      : 0.024357 s [  0.22%]
            Visualization time                   : 0.000000 s [  0.00%]
            Total optimization time              : 11.011846 s [100.00%]

**Comment by anugrahjo** [comment] 2024-08-10 18:56
Thanks for raising the issue. The issue was fixed in the GitHub repo. However, it won't reflect on PyPI until the next patch release.

**Comment by anugrahjo** [comment] 2024-10-13 23:55
The issue is corrected in the latest release on PyPI.

**Closed as completed by anugrahjo** 2024-10-13 23:55 UTC
